-- =============================================
-- EcoQuest Seed Data
-- Run AFTER migrations/001_init.sql
-- =============================================

-- Seed Badges
INSERT INTO public.badges (name, icon_key, description) VALUES
  ('First Steps',       'Sprout',   'Completed your very first quiz!'),
  ('Recycling Rookie',  'Recycle',  'Mastered the basics of recycling.'),
  ('Energy Saver',      'Wind',     'Completed the Energy module.'),
  ('Water Wizard',      'Droplets', 'Completed the Water Conservation module.'),
  ('Green Learner',     'Leaf',     'Completed 5 learning modules.'),
  ('Quiz Champion',     'Trophy',   'Scored 100% on any quiz.'),
  ('Streak Starter',    'Flame',    'Maintained a 3-day learning streak.'),
  ('Eco Warrior',       'Shield',   'Earned 1000 Eco Points.'),
  ('Game Master',       'Gamepad2', 'Played all 5 games at least once.'),
  ('Carbon Crusher',    'Globe',    'Completed the Carbon Footprint module.')
ON CONFLICT (name) DO NOTHING;

-- Note: Quizzes are created by teachers via the app UI.
-- Below is an example teacher account you can insert AFTER running the auth setup.
-- Replace password_hash with a real bcrypt hash generated by your app.

-- Example: INSERT INTO public.users (email, password_hash, display_name, role)
-- VALUES ('teacher@ecoquest.com', '$2b$12$...bcrypt_hash...', 'EcoTeacher', 'teacher');
